on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 6'
    
jobs:
  publish:
    runs-on: ubuntu-latest
      
    name: Build Chrome OS releases database
    steps:
      - name: download repo
        uses: actions/checkout@v4
      
      - name: cache downloads
        uses: actions/cache@v4
        with:
          path: downloads
          key: downloads-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            downloads-${{ github.ref }}
      
      - name: install deps
        run: |
          set -x
          sudo apt update && sudo apt install -y vboot-kernel-utils binwalk pcregrep
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt

      # inline because idk if gh workflows goes back to the old directory after every cmd like how makefile would
      - name: download old artifacts
        run: |
          wget https://github.com/crosbreaker/chromeos-releases-data/raw/main/downloads.tgz
          mkdir -p downloads
          tar xvf downloads.tgz -C downloads/
          rm -rf downloads.tgz
      
      - name: run build
        run: |
          set -x
          source .venv/bin/activate
          python3 main.py

      - name: upload database as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data/
          compression-level: 9
      
      - name: upload downloads as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloads
          path: downloads/
          compression-level: 9

      - name: publish database
        run: |
          set -x
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
          cd data
          git clone "https://${{ secrets.GH_TOKEN }}@github.com/crosbreaker/chromeos-releases-data" -b main
          cd chromeos-releases-data
          cp ../data.json ./
          if [ ! "$(git status -s)" ]; then
            exit 0
          fi
          git add .
          git commit -s -m "update data.json"
          
          cd ../../downloads
          rm -rf ./git
          tar -czf ../data/chromeos-releases-data/downloads.tgz ./
          cd -
          git add .
          git commit -s -m "update downloads.tgz"

          git push origin main

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
